function c = max_concurrence(c1, c2, c3)
% MAX_CONCURRENCE  Maximum concurrence generated by 2q gates with canonical parameters [c1, c2, c3].
%  c = max_concurrence(c1, c2, c3)
%
% Returns the maximum concurrence generated by 2q gates with canonical
% parameters [c1, c2, c3], starting from a tensor state.

%! B. Kraus and J. I. Cirac, "Optimal creation of entanglement using a two-qubit gate", PRA 63, 062309 (2001).
% Ville Bergholm 2006-2008


c = max(abs(sin(c1-c2)), abs(sin(c2-c3)));
c = max(c, abs(sin(c3-c1)));
c = max(c, abs(sin(c1+c2)));
c = max(c, abs(sin(c2+c3)));
c = max(c, abs(sin(c3+c1)));
